# Generated by Django 2.0.4 on 2018-06-20 14:14

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_interested'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='avatar',
            field=models.FileField(default='image/default.PNG', max_length=300, upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
