# Generated by Django 2.0.4 on 2018-06-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20180620_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='photo'),
        ),
    ]
