# Generated by Django 2.0.4 on 2018-06-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20180620_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.FileField(blank=True, default='default.PNG', max_length=300, null=True, upload_to='photo'),
        ),
    ]
