# Generated by Django 2.0.4 on 2018-06-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20180620_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.FileField(blank=True, default='photo/default.PNG', max_length=300, null=True, upload_to='photo/'),
        ),
    ]
