# Generated by Django 2.0.4 on 2018-06-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20180621_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientavatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('avatar', models.FileField(blank=True, max_length=300, null=True, upload_to='photo/')),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='avatar',
        ),
    ]
